from .regions import RegionName as R
from rule_builder import Rule, True_, HasAll, Has, HasAny,CanReachRegion
from typing import TYPE_CHECKING
from .StateHelpers import can_destroy_red_planks, CanReachHeight, can_destroy_wood_grave, can_destroy_stone_grave, \
    can_defeat_rattlehag, can_defeat_meatbag, HasLocationGroup
from .items import ProgressionItem as ProgItem, Events, UsefulItem


if TYPE_CHECKING:
    from world import SupralandWorld

ENTRANCE_RULES: dict[tuple[R, R], Rule["SupralandWorld"]] = {
    (R.Intro, R.RV): can_destroy_red_planks,
    (R.RV, R.Intro): can_destroy_red_planks,
    (R.RV, R.D1): True_(),
    (R.RV, R.SF): can_destroy_red_planks,
    (R.D1, R.RV): True_(),
    (R.D1, R.D2): CanReachHeight(1),
    (R.D1, R.RC): Has(ProgItem.Strong) & CanReachHeight(4),
    (R.D2, R.D1): True_(),
    (R.D2, R.D3): Has(ProgItem.ProgGun),
    (R.D2, R.RC): CanReachHeight(3) | HasAll(ProgItem.ProgTrans, ProgItem.Buckle),
    #(R.D2, R.AF1): CanReachRegion(R.AF1),
    (R.D3, R.D2): True_(),
    (R.D3, R.BV): HasAll(ProgItem.ProgCube, ProgItem.ProgGun, ProgItem.ProgForceBeam, ProgItem.Buckle) & Has(ProgItem.ProgSpeedJump, 4),
    (R.D3, R.RC): Has(ProgItem.ProgForceBeam, 2),
    (R.D3, R.FR): HasAll(ProgItem.ProgCube, ProgItem.ProgGun) | Has(ProgItem.Buckle) | Has(ProgItem.Strong),
    (R.D3, R.RH): Has(ProgItem.Buckle),
    (R.D3, R.BFB1): CanReachRegion(R.BFB1) & Has(ProgItem.ProgTrans, 2) & CanReachHeight(3) & can_destroy_red_planks,
    (R.D3, R.GC): Has(Events.MB),
    (R.RC, R.D1): Has(ProgItem.Strong) & (Has(ProgItem.ProgForceBeam) | CanReachHeight(5)),
    (R.RC, R.D2): HasAny(ProgItem.ProgGun, ProgItem.ProgForceBeam) | CanReachHeight(10),
    (R.RC, R.D3): Has(ProgItem.ProgForceBeam),
    (R.RC, R.LV): Has(ProgItem.ProgForceBeam, 2),
    (R.LV, R.RC): CanReachRegion(R.GC),
    (R.LV, R.GC): Has(ProgItem.ProgForceBeam, 3) & HasAll(ProgItem.Buckle, ProgItem.ProgCube),
    (R.LV, R.D3): True_(),
    (R.GC, R.LV): Has(ProgItem.ProgForceBeam, 2),
    (R.GC, R.BH_GC): HasAll(ProgItem.ProgForceBeam, ProgItem.ProgTrans, ProgItem.ProgCube, ProgItem.Buckle),
    (R.GC, R.D3): Has(Events.MB),
    (R.BH_GC, R.GC): CanReachHeight(8),
    (R.BH_GC, R.BFB1): Has(ProgItem.ProgTrans) & CanReachRegion(R.GC),
    (R.FR, R.D3): Has(ProgItem.Strong) | Has(ProgItem.Buckle) | can_destroy_stone_grave,
    (R.BC, R.AF1): True_(),
    #(R.AF1, R.BC): CanReachRegion(R.BC),
    (R.AF1, R.CT): (can_destroy_red_planks | CanReachHeight(3)) & Has(ProgItem.ProgCube) & Has(ProgItem.ProgForceBeam, 3),
    (R.AF1, R.D2): Has(ProgItem.Buckle),
    (R.AF1, R.AF2): Has(ProgItem.ProgCube) & can_destroy_red_planks & CanReachHeight(3), # Chest91
    (R.AF1, R.AF4): Has(ProgItem.Stomp),
    #(R.AF1, R.SF): CanReachRegion(R.SF),
    (R.AF2, R.AF1): can_destroy_wood_grave,
    (R.AF2, R.AF3): HasAny(ProgItem.Stomp, ProgItem.ProgCube) | CanReachHeight(5),
    (R.AF2, R.AF4): Has(ProgItem.Stomp),
    #(R.AF2, R.SF): CanReachRegion(R.SF),
    (R.AF3, R.AF2): HasAny(ProgItem.Stomp, ProgItem.ProgCube) | CanReachHeight(5),
    (R.AF4, R.AF1): Has(ProgItem.Stomp),
    (R.AF4, R.AF2): Has(ProgItem.ProgCube) | CanReachHeight(5),
    #(R.AF4, R.BSF): True_(),
    (R.SF, R.AF1): True_(),
    (R.SF, R.AF2): CanReachHeight(8),
    (R.SF, R.RV): Has(ProgItem.Buckle),
    (R.SF, R.BSF): Has(ProgItem.ProgGun, 2) & can_destroy_red_planks,
    (R.BSF, R.AF4): Has(ProgItem.Stomp),
    (R.BSF, R.SF): True_(),
    (R.BSF, R.BC_BG): HasAll(ProgItem.ProgGun, ProgItem.ProgCube),
    #(R.BC_BG, R.BSF): True_(),
    (R.BC_BG, R.BC_AG): HasAny(ProgItem.Buckle, ProgItem.Strong) | HasAll(ProgItem.ProgGun, ProgItem.ProgCube),
    (R.BC_AG, R.BC_BG): HasAny(ProgItem.Buckle, ProgItem.Strong),
    (R.BC_AG, R.BC_IN): can_destroy_red_planks & (HasAny(ProgItem.ProgTrans, ProgItem.Strong) | HasAll(ProgItem.ProgCube, ProgItem.ProgGun)),
    (R.BC_IN, R.BC_BG): can_destroy_red_planks & (HasAny(ProgItem.ProgTrans, ProgItem.Strong) | HasAll(ProgItem.ProgCube, ProgItem.ProgGun)),
    (R.RH, R.D3): True_(),
    (R.RH, R.AF_RH): can_defeat_rattlehag,
    (R.RH, R.BV): Has(ProgItem.ProgTrans) & CanReachHeight(5),
    (R.AF_RH, R.RH): True_(),
    (R.AF_RH, R.BF_PC): HasAll(ProgItem.Buckle, ProgItem.ProgCube) & can_destroy_red_planks,
    (R.BF_PC, R.PC): HasAll(ProgItem.ProgForceBeam, ProgItem.ProgTrans) ,
    (R.BF_PC, R.CT): HasAll(ProgItem.Strong, ProgItem.ProgCube, ProgItem.ProgForceBeam) | (HasAll(ProgItem.ProgForceBeam, ProgItem.ProgCube) & can_destroy_red_planks & CanReachHeight(4)),
    (R.PC, R.CT): HasAll(ProgItem.ProgCube, ProgItem.ProgForceBeam),
    #(R.CT, R.AF1): True_(),
    #(R.CT, R.PC): True_(),
    (R.CT, R.BF_PC): HasAll(ProgItem.ProgForceBeam, ProgItem.Strong, ProgItem.ProgCube),
    (R.BV, R.D3): Has(ProgItem.Buckle),
    (R.BV, R.RH): Has(ProgItem.ProgTrans) & CanReachHeight(5),
    (R.BV, R.BH_BV): CanReachHeight(8),
    #(R.BV, R.BFB1): True_(),
    (R.BH_BV, R.BV): CanReachHeight(8),
    (R.BFB1, R.BH_GC): CanReachHeight(5),
    (R.BFB1, R.BV): HasAll(ProgItem.ProgTrans, ProgItem.Buckle),
    (R.BFB1, R.D3): Has(ProgItem.ProgTrans, 2) & CanReachHeight(5) & can_destroy_red_planks,
    (R.BFB1, R.BFB2): Has(ProgItem.GreenMoon, 2) & HasAll(ProgItem.ProgTrans, ProgItem.ProgGun, ProgItem.ProgForceBeam),
    #(R.BFB2, R.BFB1): True_(),
    (R.BFB2, R.BFB3): HasAll(ProgItem.ProgForceBeam, ProgItem.ProgCube, ProgItem.ProgTrans),
    #(R.BFB3, R.BFB2): True_(),
    (R.BFB3, R.BA): Has(ProgItem.ProgForceBeam, 2) & HasAll(ProgItem.ProgGun, ProgItem.ProgCube, ProgItem.ProgTrans),
    #(R.BA, R.BFB3): True_(),
    (R.BA, R.LV): can_defeat_meatbag & CanReachHeight(8),
    (R.BA, R.GC): can_defeat_meatbag & CanReachHeight(8),
}

PIPE_RULES = {
    #(R.D2, R.RC): True_(),
    (R.D2, R.AF3): Has(ProgItem.Stomp),
    (R.RC, R.D2): Has(UsefulItem.Shell, 6),
    (R.FR, R.BC): HasAll(ProgItem.ProgCube, ProgItem.ProgGun) & CanReachHeight(5),
    #(R.FR, R.AF_RH): True_(),
    (R.BC, R.FR): Has(ProgItem.Buckle),
    (R.AF3, R.D2): Has(ProgItem.Buckle),
    (R.RH, R.BH_BV): Has(ProgItem.ProgTrans) & CanReachHeight(8),
    (R.AF_RH, R.FR): Has(ProgItem.ProgForceBeam) | CanReachHeight(5),
    (R.AF_RH, R.CA): HasLocationGroup("Star", 166),
    #(R.CT, R.CT): HasAll(ProgItem.ProgForceBeam, ProgItem.Buckle), # Jank
    (R.BH_BV, R.RH): True_(),
    #(R.BFB1, R.BA): True_(),
    (R.BA, R.BFB1): True_(),
    #(R.CA, R.AF_RH): True_(),
    (R.BF_PC, R.AF_RH): Has(ProgItem.ProgForceBeam, 2),
    (R.BF_PC, R.PC): Has(ProgItem.ProgCube), # One way
}