
from .locations import LocationName as L, LocationGroup as LG
from .regions import RegionName as R
from .items import ProgressionItem as P, Events as E, UsefulItem as U
from .StateHelpers import *
from .rule_builder import *

# Chest91 Helper: CanReachHeight(3) & can_destroy_red_planks

MAIN_LOCATION_RULES: dict[L, Rule["SupralandWorld"]] = {
    L.RH: can_defeat_rattlehag,
    L.MB: can_defeat_meatbag,
    L.BP_UnlockMap_2: Has(P.Buckle),
    L.BuyBelt2_2: True_(),
    L.BuyChestDetector_30: HasAll(P.Buckle, P.ProgTrans),
    L.BuyChestDetectorRadius: Has(E.MB),
    L.BuyDoubleJump2: True_(),
    L.BuyDoubleJump_786: Has(P.ProgCube),
    L.BuyForceBeamGold: True_(),
    L.BuyForceBlock3: True_(),
    L.BuyForceBlock_695: Has(P.ProgSword),
    L.BuyGun2_2: True_(),
    L.BuyGunAlt_478: Has(P.ProgGun) & can_destroy_red_planks,
    L.BuyGunCriticalDamage_1496: True_(),
    L.BuyGunCriticalDamageChance2_1856: True_(),
    L.BuyGunCriticalDamageChance3_3189: True_(),
    L.BuyGunCriticalDamageChance4_198: True_(),
    L.BuyGunCriticalDamageChance_1426: True_(),
    L.BuyGunDamage_15_1234: True_(),
    L.BuyGunDamage_5_235: CanReachHeight(5),
    L.BuyGunRefillSpeed_66_478: True_(),
    L.BuyGunRefillSpeed_67_198: True_(),
    L.BuyGunRefillSpeedx2_374: True_(),
    L.BuySilentFeet2: CanReachRegion(R.BF_PC) & CanReachHeight(3) & can_destroy_red_planks,
    L.BuyGunRefireRate50_506: True_(),
    L.BuySilentFeet_902: True_(),
    L.BuyGunSpeedx2_436: Has(P.ProgCube) & Has(P.ProgGun, 2) & CanReachRegion(R.AF4),
    L.BuyHealth_15_765: (CanReachHeight(5) & Has(P.Buckle)) | Has(P.ProgCube),
    L.BuyHealth_16_457: True_(),
    L.BuyHealth_17: True_(),
    L.BuyHealth_5: True_(),
    L.BuyHealthRegen2_695: can_destroy_red_planks,
    L.BuyHealthRegenMax10_330: True_(),
    L.BuyHealthRegenMax5_1162: True_(),
    L.BuyShieldBreaker_1026: True_(),
    L.BuyShowProgress2_2: True_(),
    L.BuySmashdownDamage_33: True_(),
    L.BuySpeedx15_2: Has(E.MB),
    L.BuySpeedx2_206: True_(),
    L.BuyStats: Has(E.MB),
    L.BuySword2_2: Has(P.RedMoon, 6),
    L.BuySword_695: True_(),
    L.BuySwordCriticalDamageChance2_2395: True_(),
    L.BuySwordCriticalDamageChance3_296: True_(),
    L.BuySwordCriticalDamageChance_1657: True_(),
    L.BuySwordDamage_11: True_(),
    L.BuySwordDamage_10_2: True_(),
    L.UpgradeSwordDamageX2_716: Has(P.ProgGun),
    L.BuyTranslocator_7: HasAll(P.ProgForceBeam, P.ProgCube, P.ProgTrans, P.ProgGun),
    L.BuyTripleJump2: True_(),
    L.BuyTripleJump_877: CanReachHeight(3) & Has(P.ProgCube),
    L.BuyUpgradeChestNum: Has(E.MB),
    L.BuyWalletx15: True_(),
    L.BuyWalletx16: True_(),
    L.BuyWalletx17_426: True_(),
    L.BuyWallet_50_737: True_(),
    L.BuyWallet_51: Has(E.MB),
    L.BuyWalletx2_986: CanReachHeight(3),
    L.Chest100_2221: HasAll(P.Strong, P.ProgSword),
    L.Chest101_2025: Has(P.ProgForceBeam),
    L.Chest102_2567: Has(P.ProgForceBeam),
    L.Chest103_3711: (Has(P.Buckle) & CanReachHeight(3)),
    L.Chest104_6073: Has(P.ProgForceBeam, 3) & Has(P.ProgCube) & CanReachHeight(4),
    L.Chest105_6706: HasAll(P.ProgForceBeam, P.Buckle) & CanReachHeight(4) & CanReachRegion(R.AF1),
    L.Chest106_8060: CanReachHeight(5) & Has(P.Buckle),
    L.Chest107_9218: Has(P.ProgForceBeam, 3) & Has(P.ProgCube) & CanReachHeight(5),
    L.Chest108_10670: HasAll(P.ProgTrans, P.ProgForceBeam),
    L.Chest109: Has(P.Strong),
    L.Chest10_1082: HasLocationGroup(LG.Star, 23) & Has(U.ShowProgress),
    L.Chest110: Has(P.ProgForceBeam),
    L.Chest111_3: Has(P.Buckle) & CanReachHeight(5),
    L.Chest112: (HasLocationGroup(LG.Star, 80) & Has(U.ShowProgress))|HasAll(P.Strong, P.ProgSword),
    L.Chest113: ((HasAll(P.ProgForceBeam, P.ProgGun) & CanReachHeight(5)) | Has(P.ProgCube)) & (Has(P.Buckle)|CanReachHeight(5)|(CanReachHeight(3) & can_destroy_stone_grave)),
    L.Chest114: HasAllCounts({P.ProgGun: 1, P.ProgCube: 1, P.ProgForceBeam: 2}),
    L.Chest115_4: HasAll(P.Buckle, P.ProgForceBeam, P.ProgGun) & CanReachHeight(4),
    L.Chest116: CanReachHeight(8),
    L.Chest117_2: HasAll(P.Strong, P.ProgSword),
    L.Chest118_2: HasAll(P.ProgForceBeam, P.ProgCube, P.ProgGun),
    L.Chest119_2: HasAll(P.Strong, P.ProgForceBeam, P.ProgSword) | HasAllCounts({P.ProgForceBeam: 3, P.ProgCube: 1}),
    L.Chest11_13130: HasAnyCount({P.ProgSpeedJump: 2, P.ProgTrans: 1}),
    L.Chest120_2: Has(P.ProgForceBeam, 3),
    L.Chest121_2: Has(P.ProgTrans),
    L.Chest122_2: HasAll(P.ProgTrans, P.ProgForceBeam, P.ProgCube, P.ProgGun),
    L.Chest123_5: CanReachHeight(8),
    L.Chest124_8: HasAll(P.ProgTrans, P.ProgForceBeam, P.ProgCube, P.ProgGun),
    L.Chest125_2: Has(P.ProgTrans, 2),
    L.Chest126: HasAll(P.Buckle, P.ProgGun) & can_destroy_red_planks,
    L.Chest127_2: HasAll(P.ProgForceBeam, P.ProgTrans) & CanReachRegion(R.BF_PC),
    L.Chest128: Has(P.ProgForceBeam) & CanReachHeight(10),
    L.Chest129_6: Has(P.ProgForceBeam),
    L.Chest12_686: HasAny(P.ProgCube, P.ProgTrans),
    L.Chest130: HasAll(P.ProgTrans, P.ProgCube) & CanReachHeight(5),
    L.Chest131: HasAll(E.RH, P.ProgTrans) & CanReachHeight(4),
    L.Chest132: Has(P.Buckle) & can_destroy_red_planks & Has(P.ProgCube),
    L.Chest133: Has(P.ProgGun) & CanReachHeight(5),
    L.Chest134_13: CanReachHeight(4) & HasAny(U.ProgHealthRegen, P.Armor, P.Health5),
    L.Chest135: Has(P.ProgGun) & CanReachHeight(4),
    L.Chest136_3: Has(P.ProgTrans),
    L.Chest137: HasAll(P.Buckle, P.Stomp, P.ProgTrans) & CanReachHeight(3),
    L.Chest138_5: Has(P.ProgTrans),
    L.Chest139: HasAll(P.ProgForceBeam, E.RH),
    L.Chest13_410: CanReachHeight(2) | Has(P.Buckle),
    L.Chest140: HasAllCounts({P.ProgForceBeam: 1, P.ProgTrans: 2, E.RH: 1}),
    L.Chest141_3: HasAll(P.ProgTrans, P.Buckle),
    L.Chest142: HasAll(P.ProgTrans, P.Buckle),
    L.Chest143: HasAll(P.Buckle, P.ProgGun),
    L.Chest144: Has(P.Buckle) | (HasAll(P.ProgCube, P.ProgGun) & CanReachHeight(3)),
    L.Chest145_2: Has(P.Buckle) | (HasAll(P.ProgCube, P.ProgGun) & CanReachHeight(4)),
    L.Chest146_2: Has(P.ProgForceBeam, 3) & Has(P.ProgCube) & CanReachHeight(4) & (Has(P.Buckle) | CanReachRegion(R.GC)),
    L.Chest147_2: can_melt_metal,
    L.Chest148_5: can_melt_metal,
    L.Chest149: can_melt_metal,
    L.Chest14_1121: reach_upper_red_crystal,
    L.Chest150: Has(P.ProgCube) & (can_break_stone| Has(P.ProgForceBeam)),
    L.Chest151_3: CanReachHeight(8) & Has(P.Buckle),
    L.Chest152_6: CanReachHeight(10),
    L.Chest153_9: HasAll(E.MB, P.Buckle),
    L.Chest154: Has(P.ProgForceBeam) & CanReachHeight(5),
    L.Chest155_2: CanReachHeight(6),
    L.Chest156_2: Has(P.Buckle),
    L.Chest157: can_defeat_gauntlet,
    L.Chest158: Has(P.ProgForceBeam),
    L.Chest159_6: HasAllCounts({P.ProgCube: 2, P.ProgForceBeam: 1, P.ProgGun: 1, P.ProgTrans: 1}),
    L.Chest15_2768: Has(P.ProgForceBeam) | (HasAll(P.Strong, P.ProgSword) & CanReachHeight(4)),
    L.Chest160: True_(),
    L.Chest161_2: Has(P.ProgTrans) & CanReachHeight(5),
    L.Chest162: Has(P.ProgGun) & CanReachHeight(4) & HasAny(P.Buckle, P.ProgTrans),
    L.Chest163: HasAll(P.Strong, P.ProgSword) & (Has(P.Buckle) | CanReachHeight(8)),
    L.Chest164: CanReachHeight(3) & HasAll(P.Strong, P.Stomp, P.ProgSword),
    L.Chest165: HasAll(P.ProgGun, P.ProgForceBeam) & CanReachHeight(8),
    L.Chest166: True_(),
    L.Chest167: Has(P.Buckle),
    L.Chest168: HasAll(P.Buckle, E.MB),
    L.Chest169: CanReachHeight(3),
    L.Chest16_5090: Has(P.Stomp) & (CanReachHeight(5) | Has(P.ProgCube)),
    L.Chest170: Has(P.ProgGun),
    L.Chest171_2: CanReachHeight(5),
    L.Chest172: CanReachHeight(2), # | CanReachRegion(R.D2)
    L.Chest17_812: reach_upper_red_crystal,
    L.Chest18_812: CanReachHeight(4),
    L.Chest19_6182: CanReachHeight(3) & HasAnyCount({P.Health5: 6, P.Health15: 3}),
    L.Chest2: CanReachHeight(2),
    L.Chest20_9041: CanReachHeight(4),
    L.Chest21_10208: True_(),
    L.Chest22_11777: can_destroy_red_planks ,
    L.Chest23_14291: CanReachHeight(4),
    L.Chest24_16178: can_destroy_red_planks,
    L.Chest25_692: reach_upper_red_crystal,
    L.Chest26_1739: CanReachHeight(5) | can_break_stone | Has(P.Buckle),
    L.Chest27_4172: True_(),
    L.Chest28_4997: CanReachHeight(8),
    L.Chest29_7214: HasAny(P.ProgCube, P.ProgTrans),
    L.Chest30_2321: True_(),
    L.Chest31_9005: reach_upper_red_crystal,
    L.Chest32_1454: True_(), # can_destroy_red_planks & Has(P.ProgCube)
    L.Chest33_1094: Has(P.ProgTrans, 2) | HasAll(P.ProgTrans, P.ProgCube),
    L.Chest34_2175: can_destroy_red_planks & CanReachHeight(4),
    L.Chest35_2137: True_(),
    L.Chest36_4639: reach_upper_red_crystal,
    L.Chest37_1815: True_(),
    L.Chest38_3995: True_(),
    L.Chest39_5860: Has(P.Buckle) | CanReachHeight(4) | (can_destroy_stone_grave & CanReachHeight(2)),
    L.Chest3_1811: (Has(P.Stomp) & CanReachRegion(R.AF2)) | can_beam_cube,
    L.Chest40_8: HasAll(P.ProgForceBeam, E.RH),
    L.Chest41_2: HasAll(P.ProgForceBeam, P.ProgCube, P.ProgTrans) & CanReachHeight(8),
    L.Chest42_1521: Has(P.ProgGun) & CanReachHeight(8),
    L.Chest43: CanReachHeight(3),
    L.Chest44_2721: CanReachHeight(4),
    L.Chest45_4075: CanReachHeight(4),
    L.Chest46: Has(P.ProgGun),
    L.Chest47: HasAll(P.ProgCube, P.Stomp) & CanReachRegion(R.BSF),
    L.Chest48_4722: Has(P.Buckle) & CanReachRegion(R.AF1),
    L.Chest49_1234: Has(P.Stomp) & CanReachHeight(4),
    L.Chest4_1544: (CanReachHeight(5) & can_beam_cube) | CanReachHeight(7),
    L.Chest50_2182: CanReachHeight(5),
    L.Chest51_1360: Has(P.Buckle) & CanReachHeight(6),
    L.Chest52_10699: CanReachHeight(3),
    L.Chest53_1192: Has(P.ProgGun) & can_destroy_red_planks,
    L.Chest54_8402: HasAllCounts({P.Stomp: 1, P.ProgForceBeam: 1, P.ProgCube: 2, P.Buckle: 1}) & can_destroy_red_planks,
    L.Chest55_3907: True_(),
    L.Chest56_5023: HasAllCounts({P.ProgGun: 2, P.ProgCube: 1}),
    L.Chest57_1073: HasAll(P.Stomp, P.ProgGun, P.Buckle) & CanReachHeight(8),
    L.Chest58: HasLocationGroup(LG.Star, 80) & Has(U.ShowProgress),
    L.Chest59: Has(P.Stomp),
    L.Chest5_1955: True_(),
    L.Chest60_2151: CanReachHeight(4) & HasAny(U.ProgHealthRegen, P.Armor, P.Health5),
    L.Chest61_2816: HasAll(P.ProgTrans, P.ProgGun),
    L.Chest62_3729: Has(P.Stomp) & CanReachRegion(R.BSF),
    L.Chest63_1565: HasAll(P.ProgCube, P.ProgGun),
    L.Chest64_1416: Has(P.ProgCube),
    L.Chest65_5150: HasAll(P.Buckle, P.ProgCube, P.ProgGun) & CanReachHeight(5),
    L.Chest66_7106: (CanReachRegion(R.BSF) & Has(P.Stomp) & CanReachHeight(2)) | can_beam_cube,
    L.Chest67: Has(P.Stomp),
    L.Chest68: CanReachHeight(5),
    L.Chest69: Has(P.ProgCube) & can_destroy_red_planks,
    L.Chest6_710: Has(P.ProgCube),
    L.Chest70: Has(P.Buckle),
    L.Chest71: Has(P.ProgGun) & CanReachRegion(R.D2),
    L.Chest72_2: HasAll(P.Buckle, P.Stomp) & CanReachHeight(8),
    L.Chest73_1605: Has(P.Buckle),
    L.Chest74: Has(P.Buckle) & can_destroy_red_planks,
    L.Chest75: HasAll(P.Buckle, P.Stomp) & CanReachHeight(3),
    L.Chest76: (can_destroy_red_planks & (Has(P.Buckle) | CanReachHeight(5))) | Has(P.ProgGun),
    L.Chest77_4: True_(),
    L.Chest78_7640: Has(P.Buckle),
    L.Chest79_2: Has(P.Buckle) & CanReachHeight(4),
    L.Chest7_818: CanReachHeight(2),
    L.Chest80_1332: HasAll(P.ProgForceBeam, P.ProgGun) & CanReachHeight(8),
    L.Chest81: HasAll(P.ProgForceBeam, P.ProgGun) & CanReachHeight(5),
    L.Chest82_4377: HasAll(P.Buckle, P.ProgForceBeam, P.ProgGun, P.ProgCube) & CanReachHeight(8),
    L.Chest83_1920: HasAll(P.ProgCube, P.ProgForceBeam, P.Strong, P.ProgSword),
    L.Chest84_3197: HasAll(P.ProgForceBeam, P.Buckle, P.ProgGun),
    L.Chest85_1892: HasAll(P.Buckle, P.ProgGun, P.ProgCube) & can_destroy_red_planks,
    L.Chest86_2441: Has(P.ProgTrans) & CanReachHeight(8),
    L.Chest87: reach_post_lockerroom & CanReachHeight(5),
    L.Chest88_1696: HasAll(P.ProgForceBeam, P.ProgCube, P.Strong, P.ProgSword),
    L.Chest89_3036: Has(P.ProgForceBeam),
    L.Chest8_878: CanReachHeight(3) & (HasAny(P.ProgCube, P.ProgTrans)),
    L.Chest90_2137: HasAll(P.ProgForceBeam, P.ProgGun) & can_destroy_red_planks,
    L.Chest91: CanReachHeight(3) & can_destroy_red_planks,
    L.Chest92: can_destroy_wood_grave,
    L.Chest93_3307: Has(P.Shell, 6),
    L.Chest94: CanReachHeight(5),
    L.Chest95_6394: HasAll(P.Buckle, P.Stomp),
    L.Chest96_8035: Has(P.Buckle),
    L.Chest97_9186: HasAll(P.Stomp, P.ProgForceBeam),
    L.Chest98_10407: Has(P.ProgForceBeam) & CanReachHeight(4),
    L.Chest99_2116: can_beam_cube,
    L.Chest9_2231: can_destroy_red_planks,
    L.Chest_622: CanReachHeight(1),
    L.UpgradeHappiness2_2: can_defeat_gauntlet & can_melt_metal & Has(P.Stomp),
    L.Juicer2: HasLocationGroup(LG.Star, 23) & Has(U.ShowProgress),
    L.Juicer3: can_destroy_red_planks,
    L.Juicer_286: True_(),
    L.Shell13_3781: can_destroy_red_planks,
    L.Shell16_5895: True_(),
    L.Shell2_1957: True_(),
    L.Shell5_1015: CanReachHeight(2) & Has(P.ProgGun),
    L.Shell9_2044: True_(),
    L.Shell_1483: True_(),
    L.DeadHero2Austin: CanReachRegion(R.AF3) | CanReachRegion(R.AF1),
    L.DeadHero2Link: CanReachHeight(3) & (HasAny(P.ProgCube, P.ProgTrans)),
    L.DeadHero3Heman: CanReachHeight(2),
    L.DeadHero3Pokemon: Has(P.Buckle) | (CanReachHeight(3) & HasAll(P.ProgCube, P.ProgGun)),
    L.DeadHero4Picard: CanReachHeight(8) & can_beam_cube,
    L.DeadHero4Santa: Has(P.Buckle),
    L.DeadHero4Santa2: True_(),
    L.DeadHero4Santa3: True_(),
    L.DeadHero_3: HasAnyCount({P.ProgForceBeam: 2, P.Buckle: 1}) ,
    L.DeadHeroGoku: True_(),
    L.DeadHeroGuybrush: HasAll(P.Stomp, P.ProgGun, P.Buckle) & CanReachHeight(8),
    L.DeadHeroIndy: reach_upper_red_crystal & Has(P.ProgGun),
}

COMPLETION_RULE = Has(E.MB)